### ISSUE TITLE
Server has to be in offline mode

### ISSUE THREAD

**Issue by YanHanr** [games647/FastLogin#783] opened 2022-04-17 15:55 UTC
### What happened?

Unable to log in to the game
#1070
plugins list：
![image](https://user-images.githubusercontent.com/101969717/163722188-ed931f12-8d48-4fce-8407-c1001c317e24.png)

### Server log

```shell
https://gist.github.com/YanHanr/52d4d1c5c582681e2f87d3e6645abf09
```

### Plugin version

1070

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment] 2022-04-17 16:01
Duplicate of #782

**Closed by games647** 2022-04-17 16:01 UTC
Labels: bug
