### ISSUE TITLE
NoSuchMethodError with Floodgate and ProtocolLib build 723

### ISSUE THREAD

**Issue by supramaxis** [games647/FastLogin#1221] opened 2024-07-06 01:54 UTC
### What happened?

probably a duplicate of #1216

I saw a new version of FastLogin just dropped so i went to update it, and also updated ProtocolLib to see if #1210 got fixed

the plugin loads but once the player joins the server, an unhandled exception occurs
btw a java.util.ConcurrentModificationException: null, is also thrown when disabling the plugin on server stop

### Steps to reproduce

1. Add FastLogin build 1322
2. Add ProtocolLib build 723
3. Try to join a server

### Plugin list

AuthMe, AxGraves, Bolt, Chunky, Essentials, EssentialsChat, FastLogin, floodgate, Geyser-Spigot, HealthBar-Reloaded [01:17:55 INFO]:  ImageFrame, LuckPerms, NBTAPI, PlaceholderAPI, PostOffice, ProtocolLib, SkinsRestorer, sleep-most, Vault

### Configuration file

https://gist.github.com/supramaxis/c8e296e8b1e299d8f00b38360fc9d1a1

### Server log

https://gist.github.com/supramaxis/05347eef760b37b75a2c8eb56184b8de

### Plugin version

v1.12-SNAPSHOT-bdd7af8

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment] 2024-07-06 06:15
This looks like an outdated Protocollib version.

**Comment by supramaxis** [comment] 2024-07-06 06:30
> This looks like an outdated Protocollib version.

Are you sure the last successful build from ProtocolLib is outdated? 
[ProtocolLib #723 (27 jun. 2024 03:12:51)](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)

**Comment by games647** [comment] 2024-07-08 10:27
I'll look into it.

**Comment by games647** [comment] 2024-07-08 10:31
Merged into 

Duplicate of #1216

**Closed by games647** 2024-07-08 10:31 UTC
Labels: bug, Floodgate/Geyser
