### ISSUE TITLE
Invalid sesion

### ISSUE THREAD

**Issue by choco3224** [games647/FastLogin#327] opened 2020-04-22 11:01 UTC
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
when a premium user uses the / premium and exits when reconnecting it puts ¨invalid session¨
### What behaviour is expected:
[//]: # (What did you expect?)

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
when a premium user uses the / premium and exits when reconnecting it puts ¨invalid session¨
### Screenshots (if applicable)
[//]: # (You can drop the files here directly)

### Plugin list:
[//]: # (This can be found by running `/pl`)
We have the plugin disabled because premium users could not connect
### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
SQL
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
latest version uploaded to spigot
### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)
 https://hastebin.com/nulowofizo.md
### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
https://hastebin.com/oyafekocox.makefile

**Comment by games647** [comment] 2020-04-22 11:32
Another duplicate of #325

**Closed by games647** 2020-04-22 11:32 UTC
Labels: bug
