### ISSUE TITLE
can't work with floodgate on velocity

### ISSUE THREAD

**Issue by BingYanchi** [games647/FastLogin#991] opened 2023-02-23 18:37 UTC
### What happened?

I used the floodgate link to create a genuine Minecraft account, but an error occurred when I logged in.
Use latest Velocity, Floodgate, FastLogin.

### What did you expect?

normal access server

### Steps to reproduce

- Use floodgate link genuine account
- Login to the server on Velocity
- Can't enter, error occurred

### Plugin list

Floodgate, FastLogin

### Configuration file

https://gist.github.com/BingYanchi/cd344caca2dccc0911cb06d1552f3448

### Server log

https://gist.github.com/BingYanchi/37a3877651b3e581844db495a6a89dac

### Plugin version

Build #1195

### Platform

Velocity

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Smart123s** [comment] 2023-02-26 19:10
FastLogin Velocity doesn't support Floodgate yet. Duplicate of https://github.com/games647/FastLogin/issues/729#issuecomment-1050530340

**Closed** 2024-07-08 09:40 UTC
Labels: bug, Floodgate/Geyser
