### ISSUE TITLE
Floodgate player name prefixes are not working with ProtocolLib

### ISSUE THREAD

**Issue by Smart123s** [games647/FastLogin#493] opened 2021-03-20 12:56 UTC
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
When I join the game, my name is Smart123s.
In the log: `Smart123s left the game`

If I delete `FastLogin.jar` from the `plugins` folder, the prefixes are added to the player's name as excepted.

### What behaviour is expected:
[//]: # (What did you expect?)
When I join the game, my name should be *Smart123s.
In the log: `*Smart123s left the game`

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Install the plugins mentioned below, and login from Bedrock Edition.

### Plugin list:
[//]: # (This can be found by running `/pl`)
AuthMe, FastLogin, Geyser-Spigot, floodgate-bukkit, ProtocolLib, Skinsrestorer

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Default DB for all plugins.
Java 14, Ubuntu 20.04, MC v1.16.5, Paper-553, No Bungeecord or Proxy
Connected to server using an Android device.
The issue is present both on LAN and on Cellular

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
[Build #968](https://ci.codemc.io/job/Games647/job/FastLogin/968/)

### Server Log:
[//]: # (No images please - only the textual representation)
None

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
*Note: other entries have not been modified*
```
autoRegister: false
secondAttemptCracked: true
switchMode: false
premiumUuid: true
nameChangeCheck: false
forwardSkin: true
premium-warning: true
mojang-request-limit: 600
auto-register-unknown: false
autoLogin: true
```

Floodgate's config:
```
username-prefix: "*"
```

Geyser's config:
```
remote:
    auth-type: floodgate
```

**Comment by t0ssox** [comment] 2021-05-03 11:42
This bug causes that a significant number of players (for my small server) cannot enter via bedrock because most have the same nickname on Bedrock and Java. Hope this will be fixed in the future.

**Comment by Smart123s** [comment] 2021-05-06 09:26
I've done some debugging and now I am even more confused than I was before.

The problem seems to be in [ProtocolLibListener.java](https://github.com/games647/FastLogin/blob/d6a02aa5385ef7eb6c8b2f2169dfae1a351ef5b8/bukkit/src/main/java/com/github/games647/fastlogin/bukkit/listener/protocollib/ProtocolLibListener.java).

Commenting out the contents of the `register()` function, or stopping the listener it from registering in any other way will make Floodgate prefixes appear. _(And yes, it also breaks the plugin.)_

However commenting out the contents of `onPacketReceiving()`, so effectively registering an empty event will cause the prefixes to be broken again. 

Switching from ProtocolLib to ProtocolSupport solved the prefix problem.
Note Java auto-login is broken with ProtocolSupport and https://github.com/games647/FastLogin/pull/494, but works fine using upstream.

**Comment by t0ssox** [comment] 2021-05-07 21:50
Thanks so much for fixing your fork (autoRegister thing), I wanted to report about this for you but I didn't know where. About Protocol plugins you are right, on ProtocolSupport prefixes works fine but I can't just switch from ProtocolLib to ProtocolSupport because most of my plugins rely on ProtocolLib and doesn't have support for ProtocolSupport (VentureChat, InteractiveChat). 

This problem is caused by bad implementation from FastLogin or its ProtocolLib problem mostly?

**Comment by Smart123s** [comment] 2021-05-08 08:15
> I wanted to report about this for you but I didn't know where.

You can report anything related to he for in it's pull request https://github.com/games647/FastLogin/pull/494

> This problem is caused by bad implementation from FastLogin or its ProtocolLib problem mostly?

I think that either Floodgate or ProtocolLib does something wrong here, because even registering an **empty** START listener will break the prefixes.

**Comment by CormacZ** [comment] 2021-09-23 01:24
I have a question, how do I use ProtocolSupport if floodgate doesn't support them yet

**Comment by Smart123s** [comment] 2021-09-23 03:34
> I have a question, how do I use ProtocolSupport if floodgate doesn't support them yet

Floodgate supports ProtocolSupport. Are you on the latest version of Floodgate/Geyser?

**Comment by CormacZ** [comment] 2021-09-24 03:21
> > I have a question, how do I use ProtocolSupport if floodgate doesn't support them yet
> 
> Floodgate supports ProtocolSupport. Are you on the latest version of Floodgate/Geyser?

oh, the support said they don't support it yet, outdated probably, ill use it now.

**Closed** 2021-12-23 11:28 UTC
Labels: bug, Floodgate
