### ISSUE TITLE
https://sessionserver.mojang.com is offline, how to solve?

### ISSUE THREAD

**Issue by SimonMage** [games647/FastLogin#953] opened 2022-12-15 18:33 UTC
### What happened?

https://sessionserver.mojang.com/ server status is offline, every premium player can join in my server, how can i do fo fixing it. The problem has appeard weeks ago.

### What did you expect?

A different website or different setting for fixing it

### Steps to reproduce

just entering on server with premium account

### Plugin list

Authme, Fastlogin

### Plugin version

Latest

### Platform

Velocity

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment] 2022-12-16 08:02
How should the plugin be able the verify the sessions then? If it is down, we cannot solve it on our end.

**Comment by SimonMage** [comment] 2022-12-23 21:00
Infact I need an alternative solution, you developed it

**Comment by games647** [comment] 2024-05-22 13:25
Duplicate of #426

**Closed by games647** 2024-05-22 13:25 UTC
Labels: bug
