### ISSUE TITLE
Plugin throws error upon player login

### ISSUE THREAD

**Issue by PeenoiseMC** [games647/FastLogin#819] opened 2022-06-16 03:29 UTC
### What happened?

Plugin doesn't work as expected. Throws an error upon player login.
![image](https://user-images.githubusercontent.com/96936249/173982824-7e3c2e8a-ae45-4cdb-9eb7-2ee618e89bbf.png)

### What did you expect?

Auto login premium player.

### Steps to reproduce

Use the [#1079](https://ci.codemc.io/job/Games647/job/FastLogin/1079/) build
Start the server
Login a premium account

### Plugin list

Authme, ProtocolLib

### Server log

```shell
[20:25:49 ERROR]: [FastLogin] Unhandled exception occurred in onAsyncPacket() for FastLogin
com.comphenix.protocol.reflect.FieldAccessException: No field with type com.mojang.authlib.GameProfile exists in class PacketLoginInStart.
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onLogin(ProtocolLibListener.java:126) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onPacketReceiving(ProtocolLibListener.java:96) ~[FastLoginBukkit.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:642) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:596) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.access$200(AsyncListenerHandler.java:48) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$2.run(AsyncListenerHandler.java:229) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$3.run(AsyncListenerHandler.java:300) ~[ProtocolLib.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-18]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-18]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Plugin version

Build #1079

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment] 2022-06-16 08:50
Please check for duplicate tickets next time. Duplicate of #809

**Closed by games647** 2022-06-16 08:50 UTC
Labels: bug
