### ISSUE TITLE
Bedrock Players won't get autologged

### ISSUE THREAD

**Issue by goosBanny** [games647/FastLogin#729] opened 2022-02-15 14:19 UTC
### What happened?

Bedrock Players are not getting automatically logged into the server.

### What did you expect?

I expected the Bedrock Players to get automatically logged in every time after they did /premium, logged out and relogged in.

BTW the prefix for FloodGate is "-".

### Steps to reproduce

1. Join through proxy as a Bedrock Player and register/login.
2. Do /premium 2 times.
3. /logout
4. Rejoin. Bedrock Players won't get auto-logged in.

### Plugin list

Velocity: AuthMeVelocity, FastLoginVelocity, FloodGate, Geyser, LuckPerms, ProtocolSupport, SkinsRestorer, ViaVersion, ViaBackwards, ViaRewind. Spigot: AuthMe, FastLogin, LuckPerms, ProtocolLib

### Configuration file

Spigot: https://www.toptal.com/developers/hastebin/uwotiqemuh.yaml  Velocity: https://www.toptal.com/developers/hastebin/umoguhuyov.yaml

### Plugin version

1.11-SNAPSHOT-033fdd5

### Platform

Velocity

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment] 2022-02-15 15:15
Please post the server log. It's important to know what FastLogin tried do and if it found the correct session.

**Comment by goosBanny** [comment] 2022-02-15 15:42
Spigot: https://www.toptal.com/developers/hastebin/zujuzehiga.sql Velocity: https://www.toptal.com/developers/hastebin/aqufivaruy.less Here you go.

**Comment by games647** [comment] 2022-02-15 15:52
There are no proxy messages in the Spigot server (Proxy requests force login). Do you followed the setup guide on the project page?

**Comment by paj1s** [comment] 2022-02-25 04:02
I have the same problem, bedrock players are not autologed and i donť know how to fix it, floodgate doesn't have prefix, both autoregister and autologin is set to true the one with the no-conflict option is set to no-conflict, still bedrock players are not autologed and /premium doesn't work.

**Comment by Smart123s** [comment] 2022-02-25 05:14
Fast login Velocity doesn't support Floodgate yet. https://github.com/games647/FastLogin/pull/649/

https://github.com/games647/FastLogin/blob/033fdd55ae105dd5bd0fb1709a87b29ee16e2981/velocity/src/main/java/com/github/games647/fastlogin/velocity/FastLoginVelocity.java#L142-L145

**Comment by paj1s** [comment] 2022-02-25 14:11
i have waterfall

**Comment by Smart123s** [comment] 2022-02-25 14:17
> i have waterfall

The original issue was opened for Velocity, so I doubt that the issue is caused by the same bug.

Could you please open a new issue, with logs & everything.

**Comment by refractored** [comment] 2022-07-24 02:02
Stale?

Works fine for me with floodgate (Bungeecord)

**Comment by Codixer** [comment] 2023-07-01 11:08
Might want to rename this issue to bedrock players don't get autologged on velocity servers

**Comment by refractored** [comment] 2023-08-01 16:38
^^

**Comment by Clyde6790pGIT** [comment] 2024-07-04 11:33
Any fixes? It's been a year

**Comment by Codixer** [comment] 2024-07-04 14:55
My best assumption is that this is an issue with how Velocity handles players and FastLogin not being able to handle them. (But it's only a guess)

For the people having this issue ( @bobhenl, @Clyde6790pGIT ) so we can look into respective configs and see if it's still an issue?

**Comment by Smart123s** [comment] 2024-07-04 15:16
@Codixer I'm not sure what you are talking about with the configs, but this issue is not related to configurations. The reason why the Floodgate integration doesn't work on FastLogin Velocity is because that feature hasn't been implemented (coded) yet. The only way to make it work is by writing the code required, and adding it to FastLogin. No configuration change will help here. This is a feature long missing, and should be a higher priority, especially now that Waterfall has been deprecated. If I'll have some spare time in the coming weeks, I'll try to take a look at it. But no promises.

**Comment by Clyde6790pGIT** [comment] 2024-07-04 15:28
> My best assumption is that this is an issue with how Velocity handles players and FastLogin not being able to handle them. (But it's only a guess)
> 
> For the people having this issue ( @bobhenl, @Clyde6790pGIT ). Could you contact me on Discord (codixer) so we can look into respective configs and see if it's still an issue?
> 

Hi, I have somehow gotten it to work, I just installed protocollib and restarted both the proxy and backend servers and wiped authme and fastlogin databases, and now it works just fine.

**Comment by Clyde6790pGIT** [comment] 2024-07-05 03:00
> My best assumption is that this is an issue with how Velocity handles players and FastLogin not being able to handle them. (But it's only a guess)
> 
> For the people having this issue ( @bobhenl, @Clyde6790pGIT ). Could you contact me on Discord (codixer) so we can look into respective configs and see if it's still an issue?

It weirdly only worked 50% of the time, if it autoregisters and doesnt auto login you permanently lose your progress unless the database has been wiped.

**Comment by Smart123s** [comment] 2024-07-05 04:55
Could you try reading the comments in [config.yml](https://github.com/games647/FastLogin/blob/main/core/src/main/resources/config.yml#L4) online? AFAIK, The comments don't get updated via plugin updates. If you are still sure that you have configured the plugin property, you should open a new issue and post your config and logs there. (If you'd also put a @Smart123s somewhere in the issue, I'd greatly appreciate that).

**Comment by Clyde6790pGIT** [comment] 2024-07-05 15:05
Hi, I'll reinstall all security plugins and wipe their databases and reconfigure it to try again, I'll tell you the results.

**Comment by Clyde6790pGIT** [comment] 2024-07-06 01:29
I am still having the same issues, it only works sometimes and then after that it locks people out of their account, when they try to login using the command every single letter and number they use is called invalid password.

**Comment by Clyde6790pGIT** [comment] 2024-07-06 01:42
![image](https://github.com/games647/FastLogin/assets/78290310/80c68ecc-3438-497d-af22-6f252e6805a7)
It autoregistered but does not autologin and basically locks people out their account, I can't find a fix for this because the plugin seems to be very fragile.

**Comment by Clyde6790pGIT** [comment] 2024-07-06 01:55
Hi, @Smart123s, I tagged you in an issue I created as you requested.

**Closed** 2024-07-08 09:40 UTC
Labels: bug, Floodgate/Geyser
