### ISSUE TITLE
Problem with bungeecord instance

### ISSUE THREAD

**Issue by kamziksvk** [games647/FastLogin#324] opened 2020-04-20 20:57 UTC
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)
Hello, I am running the latest build of your plugin on our bungeecord network and FastLogin keeps spamming the bungeecord console like this: https://pastebin.com/0V98JjBe
This error appears hundreds of times per day

### What behaviour is observed:
[//]: # (What happened?)
Console spamming - https://pastebin.com/0V98JjBe

### What behaviour is expected:
[//]: # (What did you expect?)
Console not spamming :)
### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
We dont know what causes this problem, it seems like that this appears during bot attacks, also for some of the regular users.
### Screenshots (if applicable)
[//]: # (You can drop the files here directly)

### Plugin list:
[//]: # (This can be found by running `/pl`)
AntiBotDeluxe10.1, AntiBungeePluginSteal, AuthMeBungeee-2.2.0-beta1, BungeePexBridge, myAlert, LiteBans, LiteAnnouncer, Plan, myAlert, myPing, quietcord

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Travertine latest version, MySQL 

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
version: 1.11-SNAPSHOT-5b1b609

### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)
https://pastebin.com/0V98JjBe

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
https://pastebin.com/B2QdWK7Z

**Comment by games647** [comment] 2020-04-21 08:49
Duplicate of #292

**Closed by games647** 2020-04-21 08:49 UTC
Labels: bug
