### ISSUE TITLE
error encryption

### ISSUE THREAD

**Issue by cicatrice74** [games647/FastLogin#417] opened 2020-11-07 16:51 UTC
i have this error on latest dev of paper-spigot 1.16.4 and latest dev of protocollib and latest dev of fastlogin:

[22:33:39 ERROR]: [FastLogin] Couldn't enable encryption
java.lang.IllegalArgumentException: Unable to find a in net.minecraft.server.v1_16_R3.NetworkManager
at com.comphenix.protocol.reflect.FuzzyReflection.getMethodByParameters(FuzzyReflection.java:261) ~[?:?]
at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.enableEncryption(VerifyResponseTask.java:180) ~[?:?]
at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:87) ~[?:?]
at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:63) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_271]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_271]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_271]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by TheCiROMG** [comment] 2020-11-07 22:28
Same problem T.T

**Comment by Kamilkime** [comment] 2020-11-08 02:38
I've made a temporary fix for that, working only on 1.16.4 - you can find it here:
https://github.com/games647/FastLogin/issues/412#issuecomment-721921736

**Comment by games647** [comment] 2020-11-08 14:09
Duplicate of #412

**Closed by games647** 2020-11-08 14:09 UTC
Labels: bug
