### ISSUE TITLE
Floodgate (plugin) support

### ISSUE THREAD

**Issue by Patbox** [games647/FastLogin#328] opened 2020-04-22 14:10 UTC
[//]: # (Lines in this format are considered as comments and will not be displayed.)
Floodgate is a plugin, that adds better integration with Geyser (proxy).
### Is your feature request related to a problem? Please describe.
[//]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])
When you setup flodgate, you can set prefix to bedrock player's names, so they will not overlap with java ones. But FastLogin prevents this functionality (aka no prefix)
### Describe the solution you'd like
[//]: # (A clear and concise description of what you want to happen.)
Add support to Floodgate/Make that FastLogin gets username after prefix is added.
### Describe alternatives you've considered
[//]: # (A clear and concise description of any alternative solutions or features you've considered.)
If you want use prefixes, there isn't any.
### Additional context
[//]: # (Add any other context or screenshots about the feature request here.)
https://github.com/GeyserMC/Floodgate
https://github.com/GeyserMC/Geyser

**Comment by games647** [comment] 2020-04-23 10:05
Do you specifically have this problem with BungeeCord or Spigot? BungeeCord shouldn't cause much issues, because it uses normal online mode connections. Only the offline UUID is set manually for online mode connections.

**Comment by Patbox** [comment] 2020-04-23 10:43
With Spigot. Also there is log, when player's login

`[12:41:58 INFO]: [Geyser-Bukkit] /127.0.0.1:45172 tried to connect!
[12:41:58 INFO]: [Geyser-Bukkit] Player connected with username TriadicPatbox
[12:42:01 INFO]: [Geyser-Bukkit] Attempting to login using floodgate mode... authentication will be encrypted
[12:42:01 INFO]: [Geyser-Bukkit] Loaded Floodgate key!
[12:42:01 INFO]: [Geyser-Bukkit] TriadicPatbox (logged in as: TriadicPatbox) has connected to remote java server on address 127.0.0.1
[12:42:01 INFO]: [floodgate-bukkit] Added $TriadicPatbox 00000000-0000-0000-0009-01fe4fcae617
[12:42:01 INFO]: UUID of player TriadicPatbox is 00000000-0000-0000-0009-01fe4fcae617
[12:42:01 INFO]: TriadicPatbox[/127.0.0.1:40598] logged in with entity id 2081 at ([world]239.7, 68.0, 390.2451)
[12:42:01 INFO]: » [Gracz] TriadicPatbox dołączył(a) do gry!
[12:42:01 INFO]: [Geyser-Bukkit] Spawned player at 239.7 68.0 390.2451
[12:42:01 INFO]: [AuthMe] TriadicPatbox logged in!
`

**Comment by Patbox** [comment] 2020-04-25 18:34
I have 2 ideas how to solving the problem with prefixes:
- Verify the players a little later, so the floodgate can change the name.
- Add detecting if someone enters with Bedrock (floodgate has api for it) and giving him a prefix manually (from the FastLogin configuration) + autologin

**Comment by XANT3R** [comment] 2020-05-04 20:08
I join the request. Will something be done about it? :)

**Comment by TheCompieter** [comment] 2020-05-17 11:19
I join too want this was just about too make an request but someone was already faster than me.

**Comment by Patbox** [comment] 2020-06-05 18:13
FastLogin should support it. Autologin (and prefixes) for Bedrock players would be useful (especially for those playing the phone). And I think Floodgate has all API needed for it.

**Comment by games647** [comment] 2020-06-06 14:23
As far as I understand Bedrock players will connect to different hostname this will be the proxy for them. In the end all players regardless of the client type will still connect to the same BungeeCord proxy. Is that correct?

**Comment by Patbox** [comment] 2020-06-06 17:33
Something like that. Gayser have 3 buildin auth modes - Offline (allows to play on offline mode servers), Online (allows to play on any server, but it requires to login into premium 
account) and Floodgate (allows to join to Online mode servers with Floodgate plugin without need for login). The first two are mostly used by players using geyser. Floodgate (one people there are intrested) need to be configured. While it's in use, Bedrock players should get additional prefix (* by default), which doesn't work with FastLogin.

The bedrock login process looks like that:
Geyser (plugin versions also works as proxy) -> Target server (Spigot/Bungee/etc). 
If target server has Floodgate, it changes some data while login process.

More info you should check GeyserMC's discord ([http://discord.geysermc.org/](http://discord.geysermc.org/)), they will probably help you more with it than I can.

**Comment by paplyk** [comment] 2020-06-08 08:29
I join the request.

**Comment by yashendra2797** [comment] 2020-06-09 11:50
Same here!

**Comment by yashendra2797** [comment] 2020-06-09 12:21
Thank you so much for the update!

**Comment by Patbox** [comment] 2020-06-09 13:03
I tested latest build and it doesn't work to me. I'm using geyser/floodgate with Tuinity (fork of paper) without bungeecord. From commit it looks like you've added support only for bungee.

**Comment by games647** [comment] 2020-06-09 13:54
My bad looks like I misunderstood the architecture. I'll add it.

**Comment by RetnaX** [comment] 2020-06-14 09:16
When will this be fixed in Spigot/Paper/Tuinity (Paper Fork)?

**Comment by games647** [comment] 2020-06-14 10:38
The problem is that both FastLogin and Floodgate operate on packet/protocol level. This makes it harder to retrieve the data. FloodGate provides method to check if player is bridged by using the player instance or using the UUID. 

The player instance isn't available at this stage and the UUID has to be retrieved using Reflection on the spoofed UUID. There is no API to check for the spoofed UUID. Furthermore ProtocolSupport seems to have no way in their API to access the spoofed UUID. So that's the remaining part that still complicated to solve.

**Comment by Tim203** [comment] 2020-06-14 11:19
If Floodgate runs the `channelRead0` before FastLogin (don't know about that) then you should be able to just use the data in the Handshake packet since we edit the hostname packet to the correct format after we have the data we need, but that is only the case if the data comes from Bungee (or Velocity with legacy mode). If the data doesn't come from Bungee, but straight from the client then we use the spoofedUUID. Since most people use it with Bungeecord you should be fine, but I can also add a `getSpoofedUUID(Channel)` to the PacketHandler class or something so it'll work always if you prefer that.

**Comment by RetnaX** [comment] 2020-06-17 14:47
I'm conquering

**Comment by Patbox** [comment] 2020-06-28 09:16
Has something changed about this?

**Comment by paplyk** [comment] 2020-06-28 10:29
We waiting for it.

**Comment by HandyHat** [comment] 2020-07-06 13:02
Weird quirk I've found - getting a floodgate player to login for the first time when fast login isn't present on the server means that they keep their prefix even when fast login is added to the server later and they login.  Technically this is a work-around, though it would be much better to get actual support (especially as floodgate support is being advertised as a feature)

**Comment by yashendra2797** [comment] 2020-07-17 21:57
So does FL work with Bungee+Floodgate? Is it only Bukkit/Spigot support that's not working?

**Comment by XANT3R** [comment] 2020-07-18 10:26
@games647 Will you do it later this year?

**Comment by mineonofficial** [comment] 2020-07-18 10:31
I join the request

**Comment by iSilviu-debug** [comment] 2020-08-02 07:03
@games647 I join the request

**Comment by Tim203** [comment] 2020-08-24 20:38
Just as a quick note for the upcoming 2.0, I implemented a AttributeKey that contains the FloodgatePlayer class (named floodgate-player). So you should have access to basically everything you need ^

**Comment by TeYroXOfficial** [comment] 2020-08-25 14:14
I joint the request. Please update plugin to be able to use it with GeyserMC :) @games647

**Comment by LoXR** [comment] 2020-09-07 10:20
Joining the request, would be really useful to autologin bedrock players on My Network.

**Comment by wtlgo** [comment] 2020-10-26 11:34
Joining the request. There should be a way to make these two awesome plugins together

**Comment by XANT3R** [comment] 2020-10-26 12:50
I am afraid FastLogin is dead.

**Comment by HandyHat** [comment] 2020-10-26 13:02
What do you mean @XANT3R

**Comment by XANT3R** [comment] 2020-10-26 13:05
@HandyHat See when the last plugin update was released on https://ci.codemc.io/job/Games647/job/FastLogin/changes and 
and when was the last time he did something on github with this plugin.

**Comment by HandyHat** [comment] 2020-10-26 13:07
I mean the repository was updated just 14 days ago, so I still have hope...

**Comment by Patbox** [comment] 2020-10-26 13:18
The last update in this repo has been made by dependabot (bot, not creator). This plugin feels little abandoned

**Comment by HandyHat** [comment] 2020-10-26 13:20
Oh yes, you are right.

**Comment by MichailiK** [comment] 2020-10-26 15:21
A plugin isn't necessarily abandoned just because there's a lack of frequent commits. The maintainer may just be busy with their own life.
Schools, Universities etc. have been opening up for a while now, which could explain the Maintainer's current absence.

**Comment by LoXR** [comment] 2020-12-12 00:55
Is there any update on this? Would love my bedrock players on my Network to be able to autologin, and not needing to /register & /login.

**Comment by iSilviu-debug** [comment] 2020-12-12 07:27
> Is there any update on this? Would love my bedrock players on my Network to be able to autologin, and not needing to /register & /login.

idem

**Comment by XANT3R** [comment] 2020-12-12 09:41
> Is there any update on this? Would love my bedrock players on my Network to be able to autologin, and not needing to /register & /login.

Never

**Comment by D-Jy-lab** [comment] 2021-01-15 06:23
BedrockPlayerManager  may work. You just need to set '- authme forcelogin {player}'.

**Comment by iSilviu-debug** [comment] 2021-01-15 11:50
> BedrockPlayerManager may work. You just need to set '- authme forcelogin {player}'.

what do you mean

**Comment by LoXR** [comment] 2021-01-15 12:04
> > BedrockPlayerManager may work. You just need to set '- authme forcelogin {player}'.
> 
> what do you mean

Its part of the command line to add in the plugin, so it auto-logs (forcelogins_ bedrock players.

**Comment by Patbox** [comment] 2021-01-15 12:17
> BedrockPlayerManager may work. You just need to set '- authme forcelogin {player}'.

It's just a not so great workaround. FastLogin still breaks stuff

**Comment by Wolfcoool** [comment] 2021-03-16 00:34
Any updates on this? It says under features "Support for Bedrock players proxied through FloodGate" but I can't seem to get it to work.

**Comment by LoXR** [comment] 2021-03-16 03:25
> Any updates on this? It says under features "Support for Bedrock players proxied through FloodGate" but I can't seem to get it to work.

You are better off using an alternative. May need to pay for it, but has worked wonders for me.

**Closed** 2021-05-16 18:50 UTC
Labels: enhancement
