### ISSUE TITLE
Error with HackedServer

### ISSUE THREAD

**Issue by ghost** [games647/FastLogin#441] opened 2021-01-10 14:51 UTC
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
when i installed fastlogin i started to get an error in the hackedserver plugin, on join player 
### What behaviour is expected:
[//]: # (What did you expect?)
helping to fix this error so that you can use hackedserver and fastlogin without errors
### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
The player entered the server, I have fastlogin plugins and hackedserver. After I installed fastlogin an error started to appear in the hackedserver
### Screenshots (if applicable)
[//]: # (You can drop the files here directly)
![errorconsole](https://user-images.githubusercontent.com/75625135/104126107-1981d300-535b-11eb-9aaf-60921d4ed677.png)

### Plugin list:
[//]: # (This can be found by running `/pl`)
![plugins1](https://user-images.githubusercontent.com/75625135/104126134-2c94a300-535b-11eb-946e-1dfb8290a930.png)
![plugins2](https://user-images.githubusercontent.com/75625135/104126139-30282a00-535b-11eb-80d5-344fab4a6f5f.png)

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Minecraft 1.16.4 Paper
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
FastLogin version 1.11-SNAPSHOT-9ff404a
### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)
https://hastebin.com/duyejumema.properties
### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
https://hastebin.com/lekuhomiqa.yaml

**Comment by games647** [comment] 2022-08-03 15:46
Duplicate of #387

**Closed by games647** 2022-08-03 15:46 UTC
Labels: bug
