### ISSUE TITLE
ERROR "ON FORCE LOGIN"

### ISSUE THREAD

**Issue by Skajuu** [games647/FastLogin#279] opened 2019-11-06 22:46 UTC
```
[23:39:33] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.5.0-SNAPSHOT
[23:39:33] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[23:39:37] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.6.0-SNAPSHOT-b2328
[23:39:37] [Server thread/INFO]: [AuthMe] SQLite Setup finished
[23:39:37] [Server thread/INFO]: [AuthMe] No supported permissions system found! Permissions are disabled!
[23:39:37] [Server thread/INFO]: [AuthMe] [LICENSE] This product includes GeoLite2 data created by MaxMind, available at https://www.maxmind.com
[23:39:37] [Server thread/INFO]: [AuthMe] AuthMe 5.6.0-SNAPSHOT build n.2328 successfully enabled!
[23:39:37] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:39:37] [Server thread/INFO]: Done (3.678s)! For help, type "help"
[23:39:38] [Server thread/INFO]: [FastLogin] Hooking into auth plugin: AuthMeHook
[23:39:40] [Craft Scheduler Thread - 3/INFO]: [FastLogin] GameProfile Skaju has a verified premium account
[23:39:40] [User Authenticator #1/INFO]: UUID of player Skaju is -------------------------------------------
[23:39:40] [Server thread/INFO]: Skaju[/192.168.100.5:57752] logged in with entity id 191 at ([world]-0.8384363936978001, 70.0, 0.2531677857372179)
[23:39:40] [Craft Scheduler Thread - 3/WARN]: [FastLogin] ERROR ON FORCE LOGIN of Skaju
java.lang.IllegalStateException: BukkitFastLoginAutoLoginEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at com.github.games647.fastlogin.bukkit.task.ForceLoginTask.callFastLoginAutoLoginEvent(ForceLoginTask.java:52) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.core.shared.ForceLoginManagement.run(ForceLoginManagement.java:44) [FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.task.ForceLoginTask.run(ForceLoginTask.java:39) [FastLoginBukkit.jar:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

**Comment by games647** [comment] 2019-11-09 12:43
Duplicate of #278

**Closed by games647** 2019-11-09 12:43 UTC
