### ISSUE TITLE
on spigot 1.17

### ISSUE THREAD

**Issue by cicatrice74** [games647/FastLogin#553] opened 2021-06-15 19:01 UTC
[20:59:13] [FastLogin Pool Thread #3/ERROR]: [FastLogin] Couldn't enable encryption
java.lang.IllegalArgumentException: wrong number of arguments
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.enableEncryption(VerifyResponseTask.java:229) [FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:116) [FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:92) [FastLoginBukkit.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by games647** [comment] 2021-06-15 19:05
Duplicate of #552

**Comment by games647** [comment] 2021-06-15 19:05
-.-

**Closed by games647** 2021-06-15 19:05 UTC
Labels: bug

**Comment by wtlgo** [comment] 2021-06-15 23:01
I have another message in the log while trying to log it. I know that the 1.17 feature is not yet implemented, but I'll leave it here in case it's helpful.
Sorry in advance, if I'm doing something wrong here

```
[01:54:40 INFO]: [FastLogin] Handling player _SmuggyPie_
[01:54:40 INFO]: [FastLogin] Requesting premium login for registered player: _SmuggyPie_
[01:54:40 ERROR]: [FastLogin] Cannot decrypt received contents
java.lang.RuntimeException: Failed to find NMS class: MinecraftEncryption
	at com.comphenix.protocol.utility.MinecraftReflection.lambda$getMinecraftClass$1(MinecraftReflection.java:2003) ~[ProtocolLib-dev507.jar:4.7.0-SNAPSHOT-b507]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2003) ~[ProtocolLib-dev507.jar:4.7.0-SNAPSHOT-b507]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.enableEncryption(VerifyResponseTask.java:217) [FastLoginBukkit-998.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:116) [FastLoginBukkit-998.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:92) [FastLoginBukkit-998.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by games647** [comment] 2021-06-16 06:49
@wtlgo That's what I meant, it's already known (the mentioned other issue), fixed and released.
