### ISSUE TITLE
viaversion 1.4.2 - b217 - travertine b55 / FastLogin - paperclip 1.8 + Viaversion

### ISSUE THREAD

**Issue by minecraft7net** [games647/FastLogin#215] opened 2018-07-22 10:00 UTC
FastLogin-b786.jar on Travertine (i have test it with waterfall / bungeecord)
also with FastLoginBungee-b838.jar

What is the output link of /viaversion dump?

https://dump.viaversion.com/ae77e9a5f5d3c02ded20521102f39bf5db3a11316e5037a3add11a5965634cb7
Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Travertine b 55

(its probably when using FastLogin on bungeecord)
How does this error happen? login? Using an item?

connection to 1.8 paperclip with viaversion

    ver
    [11:52:50 INFO]: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
    [11:52:50 INFO]: Error obtaining version information
    pl
    [11:52:51 INFO]: Plugins (1): ViaVersion

Is there an error in the console? Use pastebin.com. Is there a kick message?

https://pastebin.com/CfZbf0VS

i have test it yesterday it was the can also when i test with 1.12 server + viaversion

without FastLogin login process works

**Comment by minecraft7net** [comment] 2018-07-22 10:01
https://github.com/MylesIsCool/ViaVersion/issues/916

**Comment by games647** [comment] 2018-07-22 13:16
I'm closing this on this end, because during a discussion on Discord we came to the conclusion that it cannot be reproduced without ViaVersion. So we will continue there.

**Closed by games647** 2018-07-22 13:16 UTC

**Comment by games647** [comment] 2018-07-23 10:58
You can close the ticket on ViaVersion. I found out that it's FastLogin's fault about the plugin message channels. They are limited to 20 characters and they are currently translated in a legacy format (by Spigot or ViaVersion) which makes them bigger than before.

**Comment by games647** [comment] 2018-07-23 10:58
Will be fixed in #216
