### ISSUE TITLE
Bedrock autologin dont work on Waterfall(proxy)

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [games647/FastLogin#719] opened 2022-02-03 08:11 UTC
### What happened?

Bedrock didnt get auto logged in

### What did you expect?

Bedrock to be auto logged in

### Steps to reproduce

Set floodgate autologin and autoregister to true

### Server log

```shell
[FastLogin] Player info LOGIN command for *asterW10 from proxy
[08:06:10 INFO]: [FastLogin] Delaying force login until join event fired?: false
[08:06:11 INFO]: [FastLogin] Player *asterW10 is connecting through Geyser Floodgate.
```

### Plugin version

version 1.11-SNAPSHOT-4a5516c

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by TDMidkwhatisxd** [comment] 2022-02-03 08:12
autologin works with java tho

**Comment by TDMidkwhatisxd** [comment] 2022-02-03 09:27
It works ok on the spigot server, but i have a second server and i wanted to make a proxy, now i have to give up -.-

**Comment by Smart123s** [comment] 2022-02-03 12:07
Duplicate of https://github.com/games647/FastLogin/issues/680

Should be fixed by https://github.com/games647/FastLogin/pull/681 or by https://github.com/games647/FastLogin/commit/8e7a91354b1e4b14d4fb0437a753248a210f1618

**Comment by TDMidkwhatisxd** [comment] 2022-02-04 15:19
will it ever be fixed?

**Comment by Smart123s** [comment] 2022-02-04 15:52
I have compiled a version for you which has the fix and the latest updates to FastLogin. [FastLoginBukkit-34375a4.zip](https://github.com/games647/FastLogin/files/8004289/FastLoginBukkit-34375a4.zip)

In the meantime, if you have some time @games647 could you take a look at https://github.com/Smart123s/FastLogin/commit/c39da0665600c93829fe6d042b9ce62374b7db98 and cherry-pick it if it's OK? I've checked, it has no conflicts with main. Github's diff looks awful, I've just moved an `if` some lines up in that commit. Here's a better diff from VSCode:

![image](https://user-images.githubusercontent.com/28480228/152558693-1bfb3cb5-74b9-4c0f-ae87-8fae9fcf8868.png)

It has the exact same changes as #680, but with a fancy commit message describing why it works. I've co-authored @BOT-Neil in the commit, since he had done most of the debugging and coding.

**Comment by TDMidkwhatisxd** [comment] 2022-02-04 19:21
Thank you. I will reply here if i find any bugs with this version

**Comment by TDMidkwhatisxd** [comment] 2022-02-05 05:32
[Geyser-BungeeCord]: asterW10 has disconnected from the Java server because of Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException

Just tried it today

**Comment by TDMidkwhatisxd** [comment] 2022-02-05 05:42
Man, i need fastlogin bungee not bukkit, I use proxy

**Comment by Smart123s** [comment] 2022-02-05 05:46
The bungee code was not modified in https://github.com/Smart123s/FastLogin/commit/c39da0665600c93829fe6d042b9ce62374b7db98 so you can use the latest unmodified version. You only have to install the patched plugin on the Bukkit servers connected to the proxy.

**Comment by TDMidkwhatisxd** [comment] 2022-02-05 05:51
[05:50:00 INFO]: [VotingPlugin] Loaded library /root/n/libraries/org/ow2/asm/asm-util/7.3.1/asm-util-7.3.1.jar
[05:50:00 ERROR]: Could not load 'plugins/FastLoginBukkit-34375a4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.Error: Unresolved compilation problems:
        The import com.github.games647.fastlogin.core.CommonUtil cannot be resolved
        The import com.github.games647.fastlogin.core.PremiumStatus cannot be resolved
        The import com.github.games647.fastlogin.core.hooks.bedrock.BedrockService cannot be resolved
        The import com.github.games647.fastlogin.core.hooks.bedrock.FloodgateService cannot be resolved
        The import com.github.games647.fastlogin.core.hooks.bedrock.GeyserService cannot be resolved
        The import com.github.games647.fastlogin.core.shared.FastLoginCore cannot be resolved
        The import com.github.games647.fastlogin.core.shared.PlatformPlugin cannot be resolved
        PlatformPlugin cannot be resolved to a type
        CommonUtil cannot be resolved
        PremiumStatus cannot be resolved to a type
        FastLoginCore cannot be resolved to a type
        FloodgateService cannot be resolved to a type
        GeyserService cannot be resolved to a type
        CommonUtil cannot be resolved
        The method getThreadFactory() is undefined for the type FastLoginBukkit
        FastLoginCore cannot be resolved to a type
        FastLoginCore cannot be resolved to a type
        FastLoginCore cannot be resolved to a type
        FastLoginCore cannot be resolved to a type
        FastLoginCore cannot be resolved to a type
        FastLoginCore cannot be resolved to a type
        FloodgateService cannot be resolved to a type
        GeyserService cannot be resolved to a type
        GeyserService cannot be resolved to a type
        FastLoginCore cannot be resolved to a type
        FloodgateService cannot be resolved to a type
        FloodgateService cannot be resolved to a type
        FastLoginCore cannot be resolved to a type
        FloodgateService cannot be resolved to a type
        FloodgateService cannot be resolved to a type
        PremiumStatus cannot be resolved to a type
        FastLoginCore cannot be resolved to a type
        FastLoginCore cannot be resolved to a type
        FastLoginCore cannot be resolved to a type
        FastLoginCore cannot be resolved to a type
        PremiumStatus cannot be resolved to a type
        PremiumStatus cannot be resolved to a type
        PremiumStatus cannot be resolved to a type
        PremiumStatus cannot be resolved to a type
        PremiumStatus cannot be resolved to a variable
        The method getPluginFolder() of type FastLoginBukkit must override or implement a supertype method
        The method getLog() of type FastLoginBukkit must override or implement a supertype method
        The method getScheduler() of type FastLoginBukkit must override or implement a supertype method
        The method sendMessage(CommandSender, String) of type FastLoginBukkit must override or implement a supertype method
        The method isPluginInstalled(String) of type FastLoginBukkit must override or implement a supertype method
        FloodgateService cannot be resolved to a type
        FloodgateService cannot be resolved to a type
        GeyserService cannot be resolved to a type
        GeyserService cannot be resolved to a type
        BedrockService cannot be resolved to a type
        The method getBedrockService() of type FastLoginBukkit must override or implement a supertype method
        FloodgateService cannot be resolved to a type
        FloodgateService cannot be resolved to a type
        GeyserService cannot be resolved to a type

**Comment by TDMidkwhatisxd** [comment] 2022-02-05 05:52
it seems that plugin wont load on my paper server

**Comment by Smart123s** [comment] 2022-02-05 06:29
I think I screwed up something with the cache or idk in my build folder, but I wasn't able to produce a proper build there. I have downloaded the code to a different folder, and now it builds correctly. Sorry for the inconveniences.

[FastLoginBukkit-34375a4-build2.zip](https://github.com/games647/FastLogin/files/8007515/FastLoginBukkit-34375a4-build2.zip)

**Comment by TDMidkwhatisxd** [comment] 2022-02-05 07:37
it woked, thank you, i ran in some issues, but i dont know how i fixed them:)

**Comment by games647** [comment] 2022-02-08 14:04
Closing this one as the mentioned commit fixes it. Many thanks to @Smart123s and @BOT-Neil

**Closed by games647** 2022-02-08 14:04 UTC
Labels: bug
