### ISSUE TITLE
okey i do all you say me but new error for me ahha

### ISSUE THREAD

**Issue by adayy12** [games647/FastLogin#882] opened 2022-08-11 12:14 UTC
### What happened?

cant load plugin #1091 

### What did you expect?

1091 

### Steps to reproduce

[14:03:13] [Server thread/ERROR]: Could not load 'plugins/FastLoginBukkit (10).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/github/games647/fastlogin/bukkit/FastLoginBukkit has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.UnsupportedClassVersionError: com/github/games647/fastlogin/bukkit/FastLoginBukkit has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_212]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_212]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_212]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_212]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_212]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_212]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_212]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d19"]

### Plugin version

1091 

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment] 2022-08-11 14:02
You also have an outdated Java version. So you can use: `1079`

**Comment by games647** [comment] 2022-08-11 14:03
Duplicate of https://github.com/games647/FastLogin/issues/828

**Closed by games647** 2022-08-11 14:03 UTC
Labels: bug
