### ISSUE TITLE
Premium user can't login in paper 1.17.1 server

### ISSUE THREAD

**Issue by HuJK** [games647/FastLogin#579] opened 2021-07-16 11:38 UTC
### What happened?
premium user can't login in paper 1.17.1 server
![image](https://user-images.githubusercontent.com/15907444/125942086-54c6536e-f6f4-4ee8-85fd-a3b8a80ee4f7.png)

### What did you expect?

Login normally

### Steps to reproduce
0. Install openjdk version "16.0.1" 
1. Download https://papermc.io/api/v2/projects/paper/versions/1.17.1/builds/107/downloads/paper-1.17.1-107.jar
2. Run paper-1.17.1-107.jar once
3. create eula.txt and set offline mode
4. Download https://github.com/AuthMe/AuthMeReloaded/releases/download/5.6.0-beta2/AuthMe-5.6.0-beta2.jar
5. Download https://github.com/dmulloy2/ProtocolLib/releases/download/4.7.0/ProtocolLib.jar
6. Download https://ci.codemc.io/job/Games647/job/FastLogin/1002/artifact/bukkit/target/FastLoginBukkit.jar
7. Put all downloaded files to plugins folder
6. Run paper-1.17.1-107.jar again
7. login with paid account
8. register and set premium by /premium twice
9. Bug occurred, he can no longer login

You can download my whole server folder here: https://drive.google.com/file/d/1lERXBneL2xPE08Ir6YZ3wwj86pHfQi5S/view?usp=sharing
Just download it, run it with ```java -jar paper-1.17.1-107.jar``` and login as a  premium user, you can reproduce this bug

### Plugin list

AuthMe-5.6.0-beta2.jar ProtocolLib.jar openjdk-16.0.1

### Configuration file

https://drive.google.com/file/d/1lERXBneL2xPE08Ir6YZ3wwj86pHfQi5S/view?usp=sharing

### Server log

```shell
[19:26:14 INFO]: [FastLogin] Requesting premium login for registered player: WhoJK
[19:26:15 ERROR]: [FastLogin] Couldn't enable encryption
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.enableEncryption(VerifyResponseTask.java:244) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:125) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:101) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: Duplicate handler name: decrypt
        at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055) ~[patched_1.17.1.jar:git-Paper-107]
        at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284) ~[patched_1.17.1.jar:git-Paper-107]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:247) ~[patched_1.17.1.jar:git-Paper-107]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[patched_1.17.1.jar:git-Paper-107]
        at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:61) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:313) ~[?:?]
        at net.minecraft.network.Connection.setEncryptionKey(Connection.java:503) ~[?:?]
        ... 11 more
```

### Plugin version

https://ci.codemc.io/job/Games647/job/FastLogin/1002/

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment] 2021-07-16 11:54
Okay that's interesting (Duplicate of #578) This seems to indicate that this is more a bug with Paper and not with ViaVersion like I assummed.

**Comment by games647** [comment] 2021-07-16 12:13
Found it. It's FastLogin issue. Older versions should work. I'm working at this moment to fix it.

**Comment by games647** [comment] 2021-07-16 12:17
Merging with #578

**Closed by games647** 2021-07-16 12:17 UTC
Labels: bug
