### ISSUE TITLE
Failed to check premium state of ...

### ISSUE THREAD

**Issue by LeCraft2Ouf** [games647/FastLogin#1011] opened 2023-03-30 15:01 UTC
### What happened?

`07:23:08 [SEVERE] [FastLogin] Failed to check premium state of WakaWase
java.io.FileNotFoundException: https://api.mojang.com/users/profiles/minecraft/WakaWase
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
    at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2048)
    at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2043)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2042)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
    at com.github.games647.craftapi.resolver.MojangResolver.findProfile(MojangResolver.java:196)
    at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:93)
    at com.github.games647.fastlogin.bungee.task.AsyncPremiumCheck.run(AsyncPremiumCheck.java:65)
    at com.github.games647.fastlogin.core.AsyncScheduler.process(AsyncScheduler.java:70)
    at com.github.games647.fastlogin.core.AsyncScheduler.lambda$runAsync$0(AsyncScheduler.java:61)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.FileNotFoundException: https://api.mojang.com/users/profiles/minecraft/WakaWase
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
    at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
    at com.github.games647.craftapi.resolver.MojangResolver.findProfile(MojangResolver.java:181)
    ... 9 more`

### What did you expect?

Nothing at all, I expect to receive no error.

### Steps to reproduce

X

### Plugin list

TAB.V3.3.1, SuperStaffChat-2.0.4-shaded, SkinRestorer, PlacerBalancer, PBServerConnector, LuckPerms, LiteBans, Infinity-Filter, FastLoginBungee, CleanMOTD, BungeeSK, BungeePackFix, AzLink

### Configuration file

https://hastebin.com/share/relaherila.yaml

### Server log

https://hastebin.com/share/vujocovupa.php

### Plugin version

LATEST

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment] 2023-03-30 15:04
Please post the exact version as mentioned in the template.

**Comment by LeCraft2Ouf** [comment] 2023-03-30 16:16
> Please post the exact version as mentioned in the template.

FastLogin version 1.12-SNAPSHOT-971b0e1

**Comment by LeCraft2Ouf** [comment] 2023-03-30 16:39
I tried with version 1.11 of fastlogin, and ProtocolLib 4.8.0 but I still get the same error

**Comment by games647** [comment] 2023-03-30 17:21
Okay, then this likely a duplicate of #998

**Comment by LeCraft2Ouf** [comment] 2023-03-30 18:48
> Okay, then this likely a duplicate of #998 and now fixed.

Or can I have the new version please?

**Comment by games647** [comment] 2023-03-31 07:35
You can download it from the CI Jenkins (development builds). There were automatically built after uploading referenced changes on that ticket. See this:

https://ci.codemc.io/job/Games647/job/FastLogin/changes

**Closed by games647** 2023-03-31 07:35 UTC
Labels: bug
