### ISSUE TITLE
Console error on FlameCord.

### ISSUE THREAD

**Issue by Rhbarber** [games647/FastLogin#813] opened 2022-06-11 21:27 UTC
### What happened?

It won't work, a console error pops up when a player login and you will get timed out when connecting. 
The lobby seems to not recognize any connection and plugins also seem to load properly on Spigot.

### What did you expect?

For it to properly work, it can't even connect to the Lobby server when using this plugin.

### Steps to reproduce

Get the latest FlameCord version and the latest DEV FastLogin version, when a player logins, this will happen. I have attached the entire log, but my login plugin does not seem to be the issue.

### Plugin list

AzLink, BungeeGuard, DynamicBungeeAuth, Floodgate, Geyser, HubBasics, LiteBans, LuckPerms, PteroBungee, ServerListPlus, SkinsRestorer

### Configuration file

https://www.toptal.com/developers/hastebin/oxiwahizoy.yaml

### Server log

```shell
https://www.toptal.com/developers/hastebin/ihigoheros.sql
```

### Plugin version

1.11-SNAPSHOT-0af22d9

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Rhbarber** [comment] 2022-06-11 21:33
Seems like totally resetting the config file worked.

**Comment by games647** [comment] 2022-06-12 06:09
Duplicate of #812

**Closed by games647** 2022-06-12 06:09 UTC
Labels: bug
