### ISSUE TITLE
Velocity Proxy Support ?

### ISSUE THREAD

**Issue by NekoMeowy** [games647/FastLogin#440] opened 2021-01-10 01:35 UTC
[//]: # (Lines in this format are considered as comments and will not be displayed.)

### Is your feature request related to a problem? Please describe.
[//]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])

### Describe the solution you'd like
[//]: # (A clear and concise description of what you want to happen.)

### Describe alternatives you've considered
[//]: # (A clear and concise description of any alternative solutions or features you've considered.)

### Additional context
[//]: # (Add any other context or screenshots about the feature request here.)
I thought that FastLogin only supports Bungeecord, and doesn't support Velocity either, I hope this can be considered!

**Comment by Lerbiq** [comment] 2021-02-03 21:20
Would like to see it too.
As far as I know, it's being worked on but it needs a complete rewrite of the plugin since velocity has its own API.

**Comment by DoctaEnkoda** [comment] 2021-03-07 13:27
up

**Comment by TheCompieter** [comment] 2021-03-11 17:14
up would love to be able too try velocity for once

**Comment by games647** [comment] 2021-06-15 11:52
Duplicate of #311

**Closed by games647** 2021-06-15 11:52 UTC
Labels: enhancement
