### ISSUE TITLE
Plugin dont works

### ISSUE THREAD

**Issue by Celophy** [games647/FastLogin#833] opened 2022-07-01 22:21 UTC
### What happened?

in 1.19 When using /premium the console give this error:

com.comphenix.protocol.reflect.FieldAccessException: No field with type com.mojang.authlib.GameProfile exists in class PacketLoginInStart.
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[ProtocolLib.jar:5.0.0-SNAPSHOT-b573]

### What did you expect?

The commando /premium should works

### Steps to reproduce

insert authme, fastlogin and protocollib

### Plugin list

authme, fastlogin and protocollib

### Configuration file

Deafult

### Server log

com.comphenix.protocol.reflect.FieldAccessException: No field with type com.mojang.authlib.GameProfile exists in class PacketLoginInStart.
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[ProtocolLib.jar:5.0.0-SNAPSHOT-b573]

### Plugin version

#1091 (Tue Jun 28 16:12:12 UTC 2022)

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by SajmonOriginal** [comment] 2022-07-02 05:18
#809

**Comment by games647** [comment] 2022-07-02 08:29
As @SajmonOriginal says, this is duplicate of #809 and there is even a pinned issue at the top of the site. Please check for existing tickets first.

**Closed by games647** 2022-07-02 08:29 UTC
Labels: bug
