### ISSUE TITLE
LuckPerms spam on check UUIDs (Insane)

### ISSUE THREAD

**Issue by zSteley** [games647/FastLogin#792] opened 2022-05-06 00:27 UTC
### What happened?

Every now and then I get a luckperms error when checking the player's UUID, this error is repeated hundreds and thousands of times, which creates two big problems.

1- The logs are huge, you can't read anything about other errors, I can't even open the log on my computer due to the big size

2- It overloads the mysql server due to the huge number of queries it performs at the same time

I requested support in LuckPerms discord, and they said to me that the error just make every permission return false, so its about FastLogin plugin that change UUIDs. They don't allow cracked servers to get support, and they will not change the way LuckPerms check the permissions on join, so, the last option to solve my issue is reporting to FastLogin.

### What did you expect?

We expect that this issue can be solved :)

### Steps to reproduce

1-Create BungeeCord server
2-Install FastLogin & LuckPerms
3-Allow cracked players to join

### Plugin list

LuckPerms, FastLogin

### Configuration file

https://www.toptal.com/developers/hastebin/firivudanu.yaml

### Server log

```shell
Can't send the entire log because of the size file is too large

This is the error that spam and create large logs and overload mysql server:
https://www.toptal.com/developers/hastebin/zoneyavanu.sql
```

### Plugin version

FastLogin version 1.11-SNAPSHOT-0bdcc93

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment] 2022-05-06 06:01
>I requested support in LuckPerms discord, and they said to me that the error just make every permission return false, so its about FastLogin plugin that change UUIDs.

FastLogin should change the UUID before LuckPerms see it. So LuckPerms only see one consistent UUID. Please activate debug logins in LuckPerms and send me the logs with `Processing ...`.

**Comment by elmaslarry** [comment] 2022-05-06 21:23
> games647

Impossible to open a 5GB log on my pc
https://imgur.com/KBNQeoZ

**Comment by elmaslarry** [comment] 2022-05-06 21:33
https://user-images.githubusercontent.com/49719896/167219258-0d141abc-5d48-4ae0-8208-2cd612b658f9.mp4

**Comment by elmaslarry** [comment] 2022-05-06 21:38
https://paste.md-5.net/asujoyocir.sql

**Comment by games647** [comment] 2022-05-07 09:15
I'll need the processing part before the error.

**Comment by elmaslarry** [comment] 2022-05-07 10:45
The issue is that  I can't open the file when it start to spam

**Comment by elmaslarry** [comment] 2022-05-07 10:45
What can I do?

**Comment by games647** [comment] 2022-05-07 11:31
I see you are using xterm, so you can use vim, nano etc. to open the file server side and scroll to the first login of that user. The user gets kicked during login. This is the time your MultiLobby plugin performs permission checks. This likely at a stage LuckPerms never got to the time to load the profile data. 

FastLogin already set the UUID, so LuckPerms running after FastLogin, should load this data then.

**Comment by elmaslarry** [comment] 2022-05-09 10:00
https://paste.md-5.net/ifucolekoc.md

**Comment by elmaslarry** [comment] 2022-05-09 10:00
This is the log just before start spamming

**Comment by games647** [comment] 2022-05-09 12:59
Yes that's perfect.

There you can see, LuckPerms just unloaded the data of that player before the check. This happens for example if the player is marked as offline (not connected) by BungeeCord. If the UUID got changed, both should be made with the newer UUID since the event fires.

In this case with your configuration, FastLogin operated as expected. With `premiumUUID` disabled, everyone gets an offline UUID. In BungeeCord we need to override to offline if the connection is in onlinemode. `0082104a-11e8-329c-9351-7e7e03c974e3` is the correct offline UUID for that player. So the question is why does LuckPerms unloads the data.

What comes to my mind is that the player actually disconnected, therefore check your logs for the timestamp where the player joins your proxy and end his/her session.

Another thing is that BungeeCord maybe doesn't mark the associated UUID with the player as online even though the player is connected. Checking the BungeeCord source code, shows that FastLogin sets the UUID similar to onlinemode before the UUID with the player is added to the list of online players. After finishing the connection setup the new UUID then gets should get used. So everything should be fine here.

Besides that I'm using the official BungeeCord and Travertine as a reference, maybe there is an issue with the fork you are using XCord, that slightly different. I don't have access to that, so I cannot analyze that part.

**Comment by elmaslarry** [comment] 2022-05-09 13:15
Okey let me check with xcord dev, thanks

**Closed** 2022-07-27 14:12 UTC
Labels: bug
