### ISSUE TITLE
Fastlogin - Geyser

### ISSUE THREAD

**Issue by PasteDev** [games647/FastLogin#899] opened 2022-08-22 15:38 UTC
### What happened?

![image](https://user-images.githubusercontent.com/42726698/185960438-ae6a189f-697c-4017-8f87-9c6a017bed36.png)

### Plugin list

https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/feature%252Fextensions/

### Server log

https://bin.bloom.host/iyasalowul

### Plugin version

#1154

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment] 2022-08-24 10:05
Duplicate of #871

**Closed by games647** 2022-08-24 10:05 UTC
Labels: bug, Floodgate/Geyser
