### ISSUE TITLE
Issues with paper 214 - Premiums not autologged in

### ISSUE THREAD

**Issue by Nextopi** [games647/FastLogin#331] opened 2020-04-25 08:25 UTC
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)

After upgrading to paper 1.15.2-214 premium players dont get automatically logged in, i have two servers that were upgraded to this version, only the heaviest one doesnt work with the latest version of paper, if I rollback fastlogin works perfectly.

Maybe this ?

https://github.com/PaperMC/Paper/commit/cb15cfa4f8ffc67d918f97224ee4ce5ed97fecc8 

### Steps/models to reproduce:
join server as premium user
???
profit

### Plugin list:

Luckperms, litebans, fastlogin, changeskin, nuvotifier, authme, skript, towny, worldguard, worldedit, protocolsupport, lwc, matrix, jobs, essentials, votingplugin, customcrafting, wolfyutilities, bungeetablistplus, ezrankspro, questcreator, gcore, coreprotect, protocollib, placerholderapi, mythicmobs, vault, venturechat, warpsystem, flightcontrol, mcmmo, mypet.

### Environment description
(Bungeecord, Paper 1.15.2-214, MariaDB,)

### Plugin version or build number (don't write latest):
1.11-SNAPSHOT-1375cf3

### Configuration:
https://hastebin.com/gexidonoti.makefile

**Comment by games647** [comment] 2020-04-25 10:11
Do you have any errors in the server log?

**Comment by Nextopi** [comment] 2020-04-25 16:58
> Do you have any errors in the server log?
> 
> > doesnt work with the latest version of paper, if I rollback fastlogin works perfectly.
> 
> Rollback FastLogin or Paper?

no errors, i had to rollback paper, it just never logged me in when I joined the server

**Comment by games647** [comment] 2020-04-25 18:07
Cod you try the newest build?

**Comment by Nextopi** [comment] 2020-04-26 03:18
Where ? there is no recent build on jenkins

**Comment by games647** [comment] 2020-04-26 10:30
I just noticed that too. There was a conflict while doing a push to both repositories.

**Comment by Patbox** [comment] 2020-04-26 17:49
Nope, it isn't

**Comment by Nextopi** [comment] 2020-04-27 07:15
Well, it isnt fixed completely, It works on second login so players have to reconnect to get logged in

**Comment by Nextopi** [comment] 2020-05-01 01:27
the problem is that paper made a patch and broke fastlogin, now the latest patch from fastlogin is bugged and doesnt work properly aswell, so you have to rollback to paper or whichever fork of it you are using, paper works fine on version 211 with fastlogin 1.11-SNAPSHOT-1375cf3

**Comment by games647** [comment] 2020-05-01 09:29
I tried using it with the newest Paper version and it worked flawlessly for me. So it requires further testing. 

Considering the previous build of FastLogin does it happen consistently with a specific setup like BungeeCord or Spigot only? I'll spend the weekend with some testing.

**Comment by Nextopi** [comment] 2020-05-01 16:29
I use it on bungeecord, I have two servers, it happens on both but the one with more plugins happens more often. the only thing I havent done is update Authme, but I dont think thats an issue... Im on version 5.6.0-SNAPSHOT-b2307 and AuthMeBungee-2.2.0-SNAPSHOT.

The easiest way for me to test this is when I login is /logout and reconnect almost always asks me for password.

**Comment by games647** [comment] 2020-05-03 07:57
It appears someone reported it to Paper directly. https://github.com/PaperMC/Paper/commit/3e9fc24b66d5f602e7d8510f160ff988c412a8d2

**Comment by Nextopi** [comment] 2020-05-04 07:17
tested the issue is still there with latest fastlogin

**Comment by games647** [comment] 2020-05-04 08:00
You need to test it with the newer version of Paper and ProtocolLib.

**Comment by Nextopi** [comment] 2020-05-05 05:17
Yes tested with newest paper protocol fastlogin and authme+authmebungee now, first time it works, but then if you /logout or your authme session expires, it doesnt logs you in again. maybe there is an issue there with sessions.

**Comment by Nextopi** [comment] 2020-05-05 22:32
I tested again today, the problem is on the bungee side I believe, I tested with paper alone and worked  perfectly the times I did logout or waited till my session expired, but when I tested the same on bungee it fails on first /logout or session expire.

I have checked all the settings, 

**paper**
```
spigot.yml
  bungeecord: true
  late-bind: true

server.properties
   online-mode=false
```

**bungeecord/waterfall** 
```
config.yml
  ip_forward: true
  online_mode: false
```
authme config https://pastebin.com/raw/Y40Cx6nj

Fastlogin: https://hastebin.com/gexidonoti.makefile
both paper and waterfall configured in mysql


So, any ideas ? I have tried everything I could think.

**Comment by games647** [comment] 2020-05-07 14:26
Thanks for the detailed description. It was very easy to reproduce then. I figured it out now. I'll push a patch.

**Background:**
Paper moved processing the join process to asynchronous. On the proxy side, BungeeCord notices that the player is connected to the server and so FastLogin sends the command to force login the player. The player is still in the login process while this message is received and therefore isn't reported to be online. Normally this command (plugin message) is delayed until the player is online (completed login phase).

**Comment by aikar** [comment] 2020-05-07 18:04
A better solution would be if you can listen to when a certain packet has been received from the post login process and send it then, as if the server is lagging, it might take them longer than 500ms to login waiting for chunk to load.

**Comment by Nextopi** [comment] 2020-05-07 18:22
yes, I made a script to wait 2 seconds to force login of my premium players... it was the only way, 1 second or less did not work, only 2 seconds and it was a server not lagging at 20tps... it was weird seeing the force login command not noticing the player online.

**Comment by games647** [comment] 2020-05-09 17:46
@aikar Thanks for look into this. Yes that's good point. Using a magic number here is also a bad practice. 

Regarding the packet listening solution. That's possible, but it requires us to listen to play phase packets (all login phase packets are still delivered). For this need to create custom packet deserializers and more. 

Because of this overhead, FastLogin will now track which call happens later, `PlayerJoinEvent` or plugin message packet. It will only fire on which happens later. This should verify that the player is online and ready for the auth plugin.

**Comment by Nextopi** [comment] 2020-05-13 04:25
Seems to be working now, one player said they saw once the "please /login" message but then he was logged in when he tried, nobody else has complained about it anymore.

Thanks for fixing it!

**Comment by Nextopi** [comment] 2020-05-13 22:14
I shouldnt have said it, i'm unlucky, actually today happened to someone.

She was AFK in one of the servers and was moved to the lobby after a while, when she went back to the server she was playing, she was asked to login. She never disconnected from the network. but she had to reconnect to log back in automatically.

Client side: 
https://paste.gg/p/anonymous/d27cf7346d2541089501b4347486749f/files/6e8a5223e3b9439ba549318a94dfbc75/raw

Server side:

https://paste.gg/p/anonymous/a174d29be7ce4c0ea6813133b799b8f8/files/6a2b82468f7f4faf98c7bd011b4b66fc/raw

**Comment by games647** [comment] 2020-05-15 12:30
This sounds more like a AuthMe issue. I opened a new issue and closing this. I'll add some debug messages too.

**Closed by games647** 2020-05-15 12:30 UTC
Labels: BungeeCord, bug
