### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by mirkocerati** [games647/FastLogin#467] opened 2021-02-13 20:20 UTC
Are there any chances for you to make FastLogin compatible with Velocity? (https://velocitypowered.com)

**Comment by x9nico** [comment] 2021-02-14 11:48
Yes please, I really need it for Velocity.

**Comment by Kociak7331** [comment] 2021-04-23 19:07
I'm joining, maybe something will finally move?

**Comment by games647** [comment] 2021-06-15 11:51
Duplicate of #311

**Closed by games647** 2021-06-15 11:51 UTC
Labels: enhancement
